---
- name: Configuring EC2
  hosts: localhost
  connection: local
  become: true
  tasks: 
   - name: Upgrading packages
     yum:
       name: "*"
       state: latest
  
   - name: Installing net-tools
     yum:
       name: net-tools
       state: latest
       update_cache: yes  

   - name: Installing vim
     yum:
       name: vim
       state: latest
       update_cache: yes  

   - name: Installing tmux
     yum:
       name: tmux
       state: latest
       update_cache: yes  

   - name: Installing lynx
     yum:
       name: lynx
       state: latest
       update_cache: yes

   - name: Installing wget
     yum:
       name: wget
       state: latest
       update_cache: yes  

   - name: Installing Kinesis Agent
     yum:
       name: aws-kinesis-agent
       state: latest