---
- name: Install and start nginx
  hosts: all
  become: true
  tasks:
   - name: Downloading nginx
     yum:
       name: nginx
       state: latest
       update_cache: yes       
  
   - name: Starting nginx
     service: 
       name: nginx
       state: started
       enabled: yes

   - name: Changing Nginx Log Dir Permission
     file: 
       path: /var/log/nginx
       mode: '0755'
       recurse: yes

   - name: Applying Kinesis-Agent Config
     copy:
       src: ../kinesis-agent/agent.json
       dest: /etc/aws-kinesis
       owner: root
       group: root
       backup: yes
       force: yes

   - name: Starting Kinesis Agent
     service:
       name: aws-kinesis-agent
       state: started
       enabled: yes